FROM pytorch/pytorch:latest

RUN pip install pytorch_transformers && \
    pip install tensorboardX && \
    pip install scikit-learn && \
    pip install tqdm && \
    pip install boto3 && \
    pip install requests && \
    pip install regex && \
    pip install pysftp && \
    pip install sentencepiece && \
    pip install flask_socketio && \
    pip install flask && \
    pip install nltk && \
    pip install matplotlib
